import { useState } from 'react';
import { useApp, getTodayAttendanceStatus } from '../../context/AppContext';

export default function StudentMarkAttendance() {
  const { state, dispatch } = useApp();
  const student = state.students.find(s => s.id === state.activeStudentId);
  const myClasses = state.classes.filter(cls => (cls.studentIds || []).includes(state.activeStudentId));

  const today = new Date().toISOString().split('T')[0];
  const [done, setDone] = useState({});
  const [code, setCode] = useState({});

  function handleMark(classId) {
    dispatch({
      type: 'MARK_ATTENDANCE',
      payload: { classId, date: today, studentId: state.activeStudentId, status: 'present' },
    });
    setDone(d => ({ ...d, [classId]: true }));
  }

  return (
    <div className="fade-up">
      <div className="label-md">Student Portal</div>
      <h1 className="headline-md" style={{ marginTop: '4px' }}>Mark Your Attendance</h1>
      <p className="body-md mt-2">
        Enter the class code provided by your teacher to mark yourself present.
      </p>

      <div className="flex-col gap-5 mt-8">
        {myClasses.map(cls => {
          const existing = getTodayAttendanceStatus(state, cls.id, state.activeStudentId);
          const marked = done[cls.id] || existing === 'present' || existing === 'late';

          return (
            <div key={cls.id} className="card" style={{ padding: '24px 28px' }}>
              <div className="flex justify-between items-center">
                <div>
                  <div className="headline-sm">{cls.name}</div>
                  <div className="body-md mt-2">{cls.code} · {cls.schedule} · {cls.room}</div>
                </div>
                {existing && (
                  <span className={`badge badge-${existing}`} style={{ fontSize: '0.8rem' }}>
                    <span className={`orb orb-${existing}`} />
                    Already {existing}
                  </span>
                )}
              </div>

              {!marked ? (
                <div className="flex gap-3 items-center" style={{ marginTop: '20px' }}>
                  <input
                    className="input"
                    placeholder="Enter attendance code from teacher…"
                    value={code[cls.id] || ''}
                    onChange={e => setCode(prev => ({ ...prev, [cls.id]: e.target.value }))}
                    style={{ flex: 1 }}
                  />
                  <button
                    className="btn-primary"
                    onClick={() => handleMark(cls.id)}
                    disabled={!code[cls.id]?.trim()}
                    style={{ opacity: !code[cls.id]?.trim() ? 0.5 : 1, cursor: !code[cls.id]?.trim() ? 'not-allowed' : 'pointer' }}
                  >
                    ✓ Mark Present
                  </button>
                </div>
              ) : (
                <div className="flex items-center gap-3" style={{
                  marginTop: '20px', padding: '14px 18px',
                  background: 'var(--primary-fixed)', borderRadius: 'var(--radius-lg)',
                }}>
                  <span style={{ fontSize: '1.2rem' }}>✅</span>
                  <div>
                    <div className="title-md" style={{ color: 'var(--on-primary-fixed-variant)' }}>Attendance Marked!</div>
                    <div className="body-md" style={{ fontSize: '0.75rem' }}>You are marked present for today's session.</div>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>

      <div className="card mt-8" style={{ background: 'var(--surface-container-low)', boxShadow: 'none' }}>
        <div className="label-md">ℹ In the real app</div>
        <p className="body-md mt-2">
          The attendance code would be a time-limited OTP or QR code generated by the backend, ensuring a student can only mark attendance when physically present.
        </p>
      </div>
    </div>
  );
}
